# 05 Final Export for Tableau

This is the last step. I'll just rename some columns so they look better in Tableau and save the final CSV file.

In [1]:
import pandas as pd

# Load the cleaned data
df = pd.read_csv("../data/processed/APY_cleaned.csv")
df.head()

,state,district,crop,crop_year,season,area,production,yield
0,Andaman and Nicobar Island,NICOBARS,Arecanut,2007,Kharif,2439.6,3415.0,1.399820
1,Andaman and Nicobar Island,NICOBARS,Arecanut,2007,Rabi,1626.4,2277.0,1.400025
2,Andaman and Nicobar Island,NICOBARS,Arecanut,2008,Autumn,4147.0,3060.0,0.737883
3,Andaman and Nicobar Island,NICOBARS,Arecanut,2008,Summer,4147.0,2660.0,0.641428
4,Andaman and Nicobar Island,NICOBARS,Arecanut,2009,Autumn,4153.0,3120.0,0.751264

## 1. Adding the underperforming column

I'll redo the math from the last notebook to make sure it's in the final file.

In [2]:
crop_medians = df.groupby('crop')['yield'].median()
df['Median_Yield'] = df['crop'].map(crop_medians)
df['Is_Underperforming'] = 0
df.loc[df['yield'] < df['Median_Yield'], 'Is_Underperforming'] = 1

df.head()

,state,district,crop,crop_year,season,area,production,yield,Median_Yield,Is_Underperforming
0,Andaman and Nicobar Island,NICOBARS,Arecanut,2007,Kharif,2439.6,3415.0,1.399820,1.234661,0
1,Andaman and Nicobar Island,NICOBARS,Arecanut,2007,Rabi,1626.4,2277.0,1.400025,1.234661,0
2,Andaman and Nicobar Island,NICOBARS,Arecanut,2008,Autumn,4147.0,3060.0,0.737883,1.234661,1
3,Andaman and Nicobar Island,NICOBARS,Arecanut,2008,Summer,4147.0,2660.0,0.641428,1.234661,1
4,Andaman and Nicobar Island,NICOBARS,Arecanut,2009,Autumn,4153.0,3120.0,0.751264,1.234661,1

## 2. Renaming columns

In [3]:
new_names = {
    'state': 'State Name',
    'district': 'District Name',
    'crop': 'Crop Type',
    'crop_year': 'Year',
    'season': 'Season',
    'area': 'Area (Hectares)',
    'production': 'Production (Tonnes)',
    'yield': 'Yield (T/Ha)'
}

df = df.rename(columns=new_names)
df.head()

,State Name,District Name,Crop Type,Year,Season,Area (Hectares),Production (Tonnes),Yield (T/Ha),Median_Yield,Is_Underperforming
0,Andaman and Nicobar Island,NICOBARS,Arecanut,2007,Kharif,2439.6,3415.0,1.399820,1.234661,0
1,Andaman and Nicobar Island,NICOBARS,Arecanut,2007,Rabi,1626.4,2277.0,1.400025,1.234661,0
2,Andaman and Nicobar Island,NICOBARS,Arecanut,2008,Autumn,4147.0,3060.0,0.737883,1.234661,1
3,Andaman and Nicobar Island,NICOBARS,Arecanut,2008,Summer,4147.0,2660.0,0.641428,1.234661,1
4,Andaman and Nicobar Island,NICOBARS,Arecanut,2009,Autumn,4153.0,3120.0,0.751264,1.234661,1

## 3. Saving the final file

In [4]:
df.to_csv("../data/processed/APY_tableau_final.csv", index=False)
print("All done! The file for Tableau is ready in the processed folder.")

All done! The file for Tableau is ready in the processed folder.